openapi: 3.0.0
info:
  title: Appeiron Challenge
  description: Manage User
  version: 1.6.0
  x-logo:
    url: ""
    altText: Appeiron Challenge

tags:
  - name: Tasks
    description: For managing tasks
  - name: User
    description: For managing users


servers:
  - url: "localhost:3000"
    description: The Local API server
    variables:
      environment:
        default: local

paths: {}

components:
  schemas:
    id:
      description: The unique identifier of the item
      type: string
      readOnly: true
      example: d555345345345as67a342a

    password:
      description: The password for the user
      type: string
      example: Uv13qwer67pLkj

    status:
      description: The item status
      type: string
      default: active
      enum:
        - active
        - inactive
      example: active

    dateCreated:
      description: The date of creation
      type: string
      format: date-time
      readOnly: true
      example: 2019-07-12T19:59:51.801Z

    dateModified:
      description: The date of the last modification
      type: string
      format: date-time
      readOnly: true
      example: 2019-07-20T19:59:51.801Z

    userCreated:
      description: The ID of the user who created the item. This refer to the `id` of the **User** Entity of **Janis ID Service**. See [User](/v2/service/id#tag/User).
      type: string
      readOnly: true
      example: 6a1fc1eeb5b68406e0487a10

    userModified:
      description: The ID of the user who last modified the item. This refer to the `id` of the **User** Entity of **Janis ID Service**. See [User](/v2/service/id#tag/User).
      type: string
      readOnly: true
      example: 7e1fc1eeb5b68406e048796

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    id:
      name: id
      in: path
      schema:
        type: string
        example: d555345345345as67a342a
      required: true
      description: The unique identifier of the item

  headers:
    x-janis-total:
      description: The total amount of records in the list
      schema:
        type: integer
        minimum: 0

  responses:

    SuccessCreateTaskResponse:
      description: Successful task created
      content:
        application/json:
          schema:
            type: object
            properties:
              completed:
                type: boolean
                description: Value of field inserted on database.
                example: false
              _id:
                type: string
                description: Mongo Id generated for task.
                example: 643edda9d7c0aff88843a999
              name:
                type: string
                description: Value of field inserted on database.
                example: Develop service to update user
              description:
                type: string
                description: Value of field inserted on database.
                example: This service will be available to update the user info
              createdAt:
                type: string
                format: date-time
                description: Value of field inserted on database.
                example: 2023-04-18T18:12:57.517Z
              updatedAt:
                type: string
                format: date-time
                description: Value of field updated on database.
                example: 2023-04-18T18:12:57.517

    SuccessUpdateTaskResponse:
      description: Successful task updated
      content:
        application/json:
          schema:
            type: object
            properties:
              completed:
                type: boolean
                description: Value of field inserted on database.
                example: false
              _id:
                type: string
                description: Mongo Id generated for task.
                example: 643edda9d7c0aff88843a999
              name:
                type: string
                description: Value of field inserted on database.
                example: Develop service to update user - UPDATED
              description:
                type: string
                description: Value of field inserted on database.
                example: This service will be available to update the user info
              createdAt:
                type: string
                format: date-time
                description: Value of field inserted on database.
                example: 2023-04-18T18:12:57.517Z
              updatedAt:
                type: string
                format: date-time
                description: Value of field updated on database.
                example: 2023-04-18T19:12:57.517

    SuccessDeleteTaskResponse:
      description: Successful task deleted
      content:
        application/json:
          schema:
            type: object
            properties:
              completed:
                type: boolean
                description: Value of field deleted on database.
                example: false
              _id:
                type: string
                description: Mongo Id deleted on database.
                example: 643edda9d7c0aff88843a999
              name:
                type: string
                description: Value of field deleted on database.
                example: Develop service to update user - UPDATED
              description:
                type: string
                description: Value of field deleted on database.
                example: This service will be available to update the user info
              createdAt:
                type: string
                format: date-time
                description: Value of field deleted on database.
                example: 2023-04-18T18:12:57.517Z
              updatedAt:
                type: string
                format: date-time
                description: Value of field deleted on database.
                example: 2023-04-18T19:12:57.517

    SuccessGetTaskResponse:
      description: Task getted by Id
      content:
        application/json:
          schema:
            type: object
            properties:
              completed:
                type: boolean
                description: Value of field on database.
                example: false
              _id:
                type: string
                description: Mongo Id of task.
                example: 643edda9d7c0aff88843a999
              name:
                type: string
                description: Value of field on database.
                example: Develop service to update user
              description:
                type: string
                description: Value of field on database.
                example: This service will be available to update the user info
              createdAt:
                type: string
                format: date-time
                description: Value of field on database.
                example: 2023-04-18T18:12:57.517Z
              updatedAt:
                type: string
                format: date-time
                description: Value of field on database.
                example: 2023-04-18T18:12:57.517

    SuccessGetTasksResponse:
      description: Tasks getted by filtering
      content:
        application/json:
          schema:
            type: object
            properties:
              completed:
                type: boolean
                description: Value of field on database.
                example: false
              _id:
                type: string
                description: Mongo Id of task.
                example: 643edda9d7c0aff88843a999
              name:
                type: string
                description: Value of field on database.
                example: Develop service to update user
              description:
                type: string
                description: Value of field on database.
                example: This service will be available to update the user info
              createdAt:
                type: string
                format: date-time
                description: Value of field on database.
                example: 2023-04-18T18:12:57.517Z
              updatedAt:
                type: string
                format: date-time
                description: Value of field on database.
                example: 2023-04-18T18:12:57.517

    SuccessLoginUserResponse:
      description: Successful login
      content:
        application/json:
          schema:
            type: object
            properties:
              token:
                type: string
                description: Value of the token.
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQwNTZjYjJiMjk1YmI4NWVjNDk3MGMiLCJuYW1lI

    BadRequest:
      description: A client error has ocurred.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                description: A message explaining the error
                type: string

    InternalError:
      description: A server error has ocurred.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                description: A message explaining the error
                type: string